### ISSUE TITLE
find_free_ports_1.default is not a function

### ISSUE THREAD

**Issue by Roaders** [samvv/node-find-free-ports#5]
```ts
import findFreePorts from 'find-free-ports';

freePorts = await findFreePorts(1, {startPort: portRangeStart, endPort: portRangeEnd});
```

your project is not correctly setup. You should be generating your d.ts with the declarations setting on the typescript compiler, not linking to source files.

**Comment by samvv** [comment]
Hi,

Thanks for pointing this out. I'll take a look at ASAP.

Sam

**Comment by samvv** [comment]
Totally forgot about this one!

Anyways, after a bit of searching I stumbled on babel/babel#2212, which changes Babel's algorithm to not assign to `module.exports` anymore. I installed a plugin that fixes this. Everything should work now.

**Comment by samvv** [comment]
Corection: this does not fix the problem. Apparently the Babel plugin I was using is not supported for Babel 7.
